version: '3.8'
services:
  yolo:
    build: .
    container_name: yolo
    ports:
      - "9090:9090"
    environment:
      - MODEL_DIR=/app/models
      - LABEL_STUDIO_URL=http://host.docker.internal:8081
      - LABEL_STUDIO_API_KEY=${LABEL_STUDIO_API_KEY}
      - LOG_LEVEL=DEBUG
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/data
    volumes:
      - ./models:/app/models
      - ./training_data:/app/training_data
      - ./cache:/app/cache
      - ~/label-studio-data:/label-studio/data:ro  # 添加这行
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"